Feature/routes
malinovaya0iriska/webpack-react-ESLint pull request #12
Opened 2022-01-04 09:50 UTC by malinovaya0iriska

2022-01-05 06:25 UTC, igorTT requested changes

2022-01-05 06:35 UTC, malinovaya0iriska commented on src/components/SignUp/SignUp.jsx
> +      '\t',
это просто форматирование вида записи, чтобы каждый ключ-значение на новой строке были

2022-01-05 17:06 UTC, igorTT requested changes
Супер-маленькая правка

2022-01-05 17:06 UTC, igorTT commented on src/components/InputField/InputField.jsx
> +export const InputField = React.memo(props => {
В будущем можешь столкнуться с такой проблемой- надо будет добавить propTypes или просто приаттачить что- нибудь к компоненту. Если будешь прикреплять после того, как обернула компонент в React.memo - можешь получить ошибку.

2022-01-05 19:10 UTC, malinovaya0iriska commented on src/components/InputField/InputField.jsx
> +export const InputField = React.memo(props => {
из-за экспорта недефолтного, имеешь в виду?

2022-01-06 05:40 UTC, igorTT approved these changes

2022-01-06 05:41 UTC, merged